apiVersion: apps/v1
kind: Deployment
metadata:
  name: handson-nestjs
  namespace: ${{ inputs.environment-name }}
  labels:
    app: handson-nestjs
spec:
  replicas: 2
  progressDeadlineSeconds: 900
  selector:
    matchLabels:
      app: handson-nestjs
  template:
    metadata:
      labels:
        app: handson-nestjs
    spec:
      containers:
        - name: handson-nestjs
          image: geraldobl58/handson-nestjs:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
          resources:
            limits:
              cpu: "0.5"
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          startupProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 45
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
