apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: handson-nestjs
  namespace: producao
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: producao.handson-nestjs.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: handson-nestjs
                port:
                  number: 80
