apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: handson-nestjs
  namespace: dev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    # - host: dev.suaaplicacao.com
    - host: 165.227.240.220
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: handson-nestjs
                port:
                  number: 80
