name: Deploy in Kubernetes

on:
  workflow_call:

jobs:
  deploy:
    name: Deploy in Kubernetes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Install doctl
        run: |
          wget https://github.com/digitalocean/doctl/releases/download/v1.102.0/doctl-1.102.0-linux-amd64.tar.gz
          tar xf doctl-1.102.0-linux-amd64.tar.gz
          sudo mv doctl /usr/local/bin
          rm doctl-1.102.0-linux-amd64.tar.gz
        
      - name: Authenticate doctl
        run: doctl auth init --access-token ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        
      - name: Set Kubeconfig
        run: |
          mkdir -p ~/.kube
          doctl kubernetes cluster kubeconfig save ${{ secrets.DIGITALOCEAN_CLUSTER_NAME }}

      - name: Deploy to Kubernetes
        uses: azure/k8s-deploy@v5
        with:
          manifests: |
            k8s/deployment.yaml
          images: |
            geraldobl58/handson-nestjs:v${{ github.run_number }}
