name: Pipeline CI/CD
run-name: Pipeline CI/CD executed by ${{ github.actor }} in ${{ github.run_number }}

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build application
        run: npm run build

  tests:
    needs: [build]
    uses: geraldobl58/handson-nestjs/.github/workflows/tests.yml@main

  release:
      name: Create release
      runs-on: ubuntu-latest
      needs: [tests]
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Login to Dockerhub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build Docker image and push to Dockerhub
          uses: docker/build-push-action@v6
          with:
            push: true
            context: .
            file: Dockerfile
            tags: |
              geraldobl58/handson-nestjs:latest
              geraldobl58/handson-nestjs:v${{ github.run_number }}

        
        
      
        
        